added code with some errors
OSlovachevska/online-book-store pull request #2
Opened 2023-09-28 10:52 UTC by OSlovachevska

2023-09-29 14:20 UTC, sokimaaa commented on src/main/java/service/BookServiceImpl.java
> +        return bookMapper.toDto(book);
```suggestion
        return bookRepository.getByID(id)
        .map(bookMapper::toDto)
        .orElseThrow(()
                -> new EntityNotFoundException("Can`t get book by id: " + id));
```

2023-09-29 14:20 UTC, sokimaaa commented on src/main/java/repository/BookRepository.java
> +    Optional<Book> getByID(Long id);
```suggestion
    Optional<Book> getById(Long id);
```

2023-09-29 14:22 UTC, sokimaaa commented on src/main/java/controller/BookController.java
> +@RequestMapping(value = "/book")
```suggestion
@RequestMapping(value = "books")
```

2023-09-29 14:22 UTC, sokimaaa commented on src/main/java/controller/BookController.java
> +    @GetMapping("{/id}")
```suggestion
    @GetMapping("{id}")
```

2023-10-02 10:01 UTC, Rommelua requested changes

2023-10-02 10:01 UTC, Rommelua commented on src/main/java/model/Book.java
> +@Table(name = "book")
```suggestion
@Table(name = "books")
```

2023-10-02 11:40 UTC, Rommelua approved these changes

2023-10-02 11:51 UTC, merged